import { Character, CharacterCategory } from '@/types/game';

export const CHARACTER_CATEGORIES: CharacterCategory[] = [
  'Tensura',
  'Dragons',
  'True Dragons',
  'Demons',
  'Angels',
  'Primordials',
  'Demi-Human',
  'Human (Hero Class)',
  'Arch-Angels',
  'Evolved Species',
];

export const CHARACTERS: Record<string, Character> = {
  rimuru: {
    id: 'rimuru',
    name: 'Rimuru Tempest',
    description: 'The Slime that became a Demon Lord',
    rarity: 'legendary',
    element: 'water',
    category: 'Tensura',
    baseStats: {
      hp: 100,
      mp: 150,
      speed: 4,
      power: 15,
      defense: 10,
      range: 200,
    },
    evolutions: [
      {
        name: 'Slime',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Human Form',
        level: 1,
        requirements: { level: 5, kills: 10 },
        statsMultiplier: 1.5,
      },
      {
        name: 'Demon Lord',
        level: 2,
        requirements: { level: 10, kills: 50 },
        statsMultiplier: 2.5,
      },
    ],
    moves: [
      {
        id: 'water_blade',
        name: 'Water Blade',
        type: 'basic',
        cooldown: 0.5,
        damage: 15,
        range: 150,
        mpCost: 5,
        description: 'A quick water slash',
      },
      {
        id: 'predator',
        name: 'Predator',
        type: 'charge',
        cooldown: 3,
        damage: 40,
        range: 100,
        mpCost: 20,
        description: 'Devour enemies in range',
      },
      {
        id: 'black_lightning',
        name: 'Black Lightning',
        type: 'special',
        cooldown: 5,
        damage: 60,
        range: 250,
        mpCost: 40,
        description: 'Lightning storm attack',
      },
      {
        id: 'megiddo',
        name: 'Megiddo',
        type: 'ultimate',
        cooldown: 15,
        damage: 150,
        range: 400,
        mpCost: 80,
        description: 'Ultimate magical destruction',
      },
    ],
  },
  benimaru: {
    id: 'benimaru',
    name: 'Benimaru',
    description: 'Commander of Tempest, wielder of flames',
    rarity: 'epic',
    element: 'fire',
    category: 'Tensura',
    baseStats: {
      hp: 120,
      mp: 100,
      speed: 5,
      power: 20,
      defense: 12,
      range: 180,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 15 },
        statsMultiplier: 1.6,
      },
      {
        name: 'Fair Oni',
        level: 2,
        requirements: { level: 10, kills: 60 },
        statsMultiplier: 2.8,
      },
    ],
    moves: [
      {
        id: 'flame_slash',
        name: 'Flame Slash',
        type: 'basic',
        cooldown: 0.6,
        damage: 20,
        range: 120,
        mpCost: 5,
        description: 'Flaming sword strike',
      },
      {
        id: 'hell_flare',
        name: 'Hell Flare',
        type: 'charge',
        cooldown: 3.5,
        damage: 50,
        range: 200,
        mpCost: 25,
        description: 'Explosive fire burst',
      },
      {
        id: 'black_flame',
        name: 'Black Flame',
        type: 'special',
        cooldown: 6,
        damage: 70,
        range: 220,
        mpCost: 45,
        description: 'Dark hellfire',
      },
      {
        id: 'flame_giant',
        name: 'Flame Giant',
        type: 'ultimate',
        cooldown: 18,
        damage: 180,
        range: 350,
        mpCost: 90,
        description: 'Summon massive fire demon',
      },
    ],
  },
  milim: {
    id: 'milim',
    name: 'Milim Nava',
    description: 'The Destroyer, oldest Demon Lord',
    rarity: 'legendary',
    element: 'storm',
    category: 'True Dragons',
    baseStats: {
      hp: 150,
      mp: 200,
      speed: 6,
      power: 30,
      defense: 15,
      range: 250,
    },
    evolutions: [
      {
        name: 'Base Form',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Dragonoid',
        level: 1,
        requirements: { level: 5, kills: 20 },
        statsMultiplier: 2,
      },
      {
        name: 'True Dragonoid',
        level: 2,
        requirements: { level: 10, kills: 80 },
        statsMultiplier: 3.5,
      },
    ],
    moves: [
      {
        id: 'dragonic_punch',
        name: 'Dragonic Punch',
        type: 'basic',
        cooldown: 0.4,
        damage: 25,
        range: 100,
        mpCost: 5,
        description: 'Powerful melee strike',
      },
      {
        id: 'drago_nova',
        name: 'Drago Nova',
        type: 'charge',
        cooldown: 4,
        damage: 60,
        range: 300,
        mpCost: 30,
        description: 'Energy explosion',
      },
      {
        id: 'drago_buster',
        name: 'Drago Buster',
        type: 'special',
        cooldown: 7,
        damage: 90,
        range: 350,
        mpCost: 50,
        description: 'Destructive dragon breath',
      },
      {
        id: 'wrath_king',
        name: 'Wrath King Satan',
        type: 'ultimate',
        cooldown: 20,
        damage: 250,
        range: 500,
        mpCost: 100,
        description: 'Catastrophic destruction',
      },
    ],
  },
  shion: {
    id: 'shion',
    name: 'Shion',
    description: 'Loyal secretary with deadly strength',
    rarity: 'epic',
    element: 'darkness',
    category: 'Tensura',
    baseStats: {
      hp: 130,
      mp: 80,
      speed: 4,
      power: 25,
      defense: 18,
      range: 120,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 15 },
        statsMultiplier: 1.7,
      },
      {
        name: 'Oni',
        level: 2,
        requirements: { level: 10, kills: 65 },
        statsMultiplier: 3,
      },
    ],
    moves: [
      {
        id: 'crushing_blow',
        name: 'Crushing Blow',
        type: 'basic',
        cooldown: 0.7,
        damage: 22,
        range: 100,
        mpCost: 5,
        description: 'Heavy sword strike',
      },
      {
        id: 'berserker',
        name: 'Berserker',
        type: 'charge',
        cooldown: 4,
        damage: 55,
        range: 150,
        mpCost: 20,
        description: 'Rage-fueled assault',
      },
      {
        id: 'hercules_edge',
        name: 'Hercules Edge',
        type: 'special',
        cooldown: 8,
        damage: 80,
        range: 180,
        mpCost: 35,
        description: 'Ultimate sword technique',
      },
      {
        id: 'cook_slash',
        name: 'Cook Slash',
        type: 'ultimate',
        cooldown: 16,
        damage: 160,
        range: 250,
        mpCost: 75,
        description: 'Culinary catastrophe',
      },
    ],
  },
  diablo: {
    id: 'diablo',
    name: 'Diablo',
    description: 'Primordial Black Demon',
    rarity: 'legendary',
    element: 'darkness',
    category: 'Primordials',
    baseStats: {
      hp: 140,
      mp: 220,
      speed: 7,
      power: 35,
      defense: 20,
      range: 280,
    },
    evolutions: [
      {
        name: 'Arch Demon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Demon Lord',
        level: 1,
        requirements: { level: 5, kills: 25 },
        statsMultiplier: 2.2,
      },
      {
        name: 'Primordial Black',
        level: 2,
        requirements: { level: 10, kills: 100 },
        statsMultiplier: 4,
      },
    ],
    moves: [
      {
        id: 'death_streak',
        name: 'Death Streak',
        type: 'basic',
        cooldown: 0.3,
        damage: 28,
        range: 200,
        mpCost: 8,
        description: 'Rapid dark strikes',
      },
      {
        id: 'temptation',
        name: 'Temptation',
        type: 'charge',
        cooldown: 3,
        damage: 65,
        range: 280,
        mpCost: 35,
        description: 'Seductive dark magic',
      },
      {
        id: 'void_collapse',
        name: 'Void Collapse',
        type: 'special',
        cooldown: 6,
        damage: 95,
        range: 320,
        mpCost: 55,
        description: 'Collapse space itself',
      },
      {
        id: 'apocalypse',
        name: 'Apocalypse',
        type: 'ultimate',
        cooldown: 18,
        damage: 280,
        range: 450,
        mpCost: 110,
        description: 'End of all things',
      },
    ],
  },
  veldora: {
    id: 'veldora',
    name: 'Veldora',
    description: 'Storm Dragon, True Dragon',
    rarity: 'legendary',
    element: 'storm',
    category: 'True Dragons',
    baseStats: {
      hp: 180,
      mp: 250,
      speed: 5,
      power: 40,
      defense: 25,
      range: 300,
    },
    evolutions: [
      {
        name: 'Sealed Dragon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Released Dragon',
        level: 1,
        requirements: { level: 5, kills: 30 },
        statsMultiplier: 2.5,
      },
      {
        name: 'True Dragon',
        level: 2,
        requirements: { level: 10, kills: 120 },
        statsMultiplier: 4.5,
      },
    ],
    moves: [
      {
        id: 'storm_breath',
        name: 'Storm Breath',
        type: 'basic',
        cooldown: 0.5,
        damage: 30,
        range: 250,
        mpCost: 10,
        description: 'Lightning breath attack',
      },
      {
        id: 'death_heralding_wind',
        name: 'Death Heralding Wind',
        type: 'charge',
        cooldown: 4.5,
        damage: 70,
        range: 300,
        mpCost: 40,
        description: 'Catastrophic storm',
      },
      {
        id: 'dragon_nova',
        name: 'Dragon Nova',
        type: 'special',
        cooldown: 8,
        damage: 110,
        range: 350,
        mpCost: 65,
        description: 'True Dragon power',
      },
      {
        id: 'chaos_storm',
        name: 'Chaos Storm',
        type: 'ultimate',
        cooldown: 22,
        damage: 320,
        range: 500,
        mpCost: 130,
        description: 'Apocalyptic tempest',
      },
    ],
  },
  shuna: {
    id: 'shuna',
    name: 'Shuna',
    description: 'Princess of Ogres, master analyst',
    rarity: 'rare',
    element: 'light',
    category: 'Tensura',
    baseStats: {
      hp: 90,
      mp: 180,
      speed: 5,
      power: 18,
      defense: 8,
      range: 220,
    },
    evolutions: [
      {
        name: 'Ogre Princess',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin Princess',
        level: 1,
        requirements: { level: 5, kills: 12 },
        statsMultiplier: 1.8,
      },
      {
        name: 'Divine Princess',
        level: 2,
        requirements: { level: 10, kills: 50 },
        statsMultiplier: 2.6,
      },
    ],
    moves: [
      {
        id: 'holy_bolt',
        name: 'Holy Bolt',
        type: 'basic',
        cooldown: 0.6,
        damage: 16,
        range: 200,
        mpCost: 7,
        description: 'Sacred light projectile',
      },
      {
        id: 'analyzer',
        name: 'Analyzer',
        type: 'charge',
        cooldown: 3.5,
        damage: 38,
        range: 220,
        mpCost: 22,
        description: 'Analyze and exploit weakness',
      },
      {
        id: 'spirit_blessing',
        name: 'Spirit Blessing',
        type: 'special',
        cooldown: 7,
        damage: 55,
        range: 240,
        mpCost: 40,
        description: 'Divine spirit power',
      },
      {
        id: 'divine_judgment',
        name: 'Divine Judgment',
        type: 'ultimate',
        cooldown: 15,
        damage: 140,
        range: 300,
        mpCost: 85,
        description: 'Heaven\'s wrath',
      },
    ],
  },
  ranga: {
    id: 'ranga',
    name: 'Ranga',
    description: 'Tempest Star Wolf, loyal companion',
    rarity: 'rare',
    element: 'storm',
    category: 'Tensura',
    baseStats: {
      hp: 110,
      mp: 120,
      speed: 7,
      power: 20,
      defense: 12,
      range: 140,
    },
    evolutions: [
      {
        name: 'Dire Wolf',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Tempest Wolf',
        level: 1,
        requirements: { level: 5, kills: 18 },
        statsMultiplier: 1.9,
      },
      {
        name: 'Star Wolf',
        level: 2,
        requirements: { level: 10, kills: 70 },
        statsMultiplier: 3.2,
      },
    ],
    moves: [
      {
        id: 'fang_strike',
        name: 'Fang Strike',
        type: 'basic',
        cooldown: 0.4,
        damage: 18,
        range: 120,
        mpCost: 4,
        description: 'Swift bite attack',
      },
      {
        id: 'lightning_claw',
        name: 'Lightning Claw',
        type: 'charge',
        cooldown: 3,
        damage: 42,
        range: 150,
        mpCost: 18,
        description: 'Electrified slash',
      },
      {
        id: 'tempest_howl',
        name: 'Tempest Howl',
        type: 'special',
        cooldown: 6,
        damage: 62,
        range: 200,
        mpCost: 32,
        description: 'Storm-summoning roar',
      },
      {
        id: 'black_lightning',
        name: 'Black Lightning',
        type: 'ultimate',
        cooldown: 14,
        damage: 145,
        range: 280,
        mpCost: 70,
        description: 'Devastating storm strike',
      },
    ],
  },
  gobta: {
    id: 'gobta',
    name: 'Gobta',
    description: 'Hobgoblin ninja, comic relief hero',
    rarity: 'common',
    element: 'water',
    category: 'Tensura',
    baseStats: {
      hp: 80,
      mp: 100,
      speed: 6,
      power: 12,
      defense: 8,
      range: 160,
      critChance: 5,
      attack: 150,
    },
    evolutions: [
      {
        name: 'Goblin',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'A simple goblin',
        benefits: 'Basic abilities',
      },
      {
        name: 'Hobgoblin',
        level: 1,
        requirements: { level: 5, kills: 10 },
        statsMultiplier: 1.6,
        lore: 'Evolved form with enhanced abilities',
        benefits: 'Increased speed and agility',
      },
      {
        name: 'Gob Ninja',
        level: 2,
        requirements: { level: 10, kills: 40 },
        statsMultiplier: 2.4,
        lore: 'Master ninja goblin',
        benefits: 'Stealth mastery, deadly strikes',
      },
    ],
    moves: [
      {
        id: 'ninja_strike',
        name: 'Ninja Strike',
        type: 'basic',
        cooldown: 0.5,
        damage: 14,
        range: 140,
        mpCost: 4,
        description: 'Quick ninja attack',
      },
      {
        id: 'shadow_clone',
        name: 'Shadow Clone',
        type: 'charge',
        cooldown: 3.5,
        damage: 32,
        range: 160,
        mpCost: 16,
        description: 'Confusing clone jutsu',
      },
      {
        id: 'water_shuriken',
        name: 'Water Shuriken',
        type: 'special',
        cooldown: 6.5,
        damage: 48,
        range: 180,
        mpCost: 28,
        description: 'Spinning water blades',
      },
      {
        id: 'ultimate_ninja',
        name: 'Ultimate Ninja Art',
        type: 'ultimate',
        cooldown: 13,
        damage: 120,
        range: 240,
        mpCost: 65,
        description: 'Secret technique!',
      },
    ],
  },
  souei: {
    id: 'souei',
    name: 'Souei',
    description: 'Master of shadows and stealth',
    rarity: 'epic',
    element: 'darkness',
    category: 'Tensura',
    baseStats: {
      hp: 100,
      mp: 130,
      speed: 8,
      power: 22,
      defense: 10,
      range: 170,
      critChance: 12,
      attack: 220,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'An ogre with shadow abilities',
        benefits: 'Shadow manipulation basics',
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 15 },
        statsMultiplier: 1.7,
        lore: 'Ninja instincts awaken',
        benefits: 'Shadow Strike and Smoke Step',
      },
      {
        name: 'Shadow Executor',
        level: 2,
        requirements: { level: 10, kills: 60 },
        statsMultiplier: 3.2,
        lore: 'Ultimate assassin powers',
        benefits: 'Backstab Mastery and Shadow Clone',
      },
    ],
    moves: [
      {
        id: 'shadow_strike',
        name: 'Shadow Strike',
        type: 'basic',
        cooldown: 0.4,
        damage: 20,
        range: 150,
        mpCost: 6,
        description: 'Swift shadow attack',
      },
      {
        id: 'phantom_slash',
        name: 'Phantom Slash',
        type: 'charge',
        cooldown: 3,
        damage: 50,
        range: 180,
        mpCost: 25,
        description: 'Multi-hit assassination',
      },
      {
        id: 'smoke_step',
        name: 'Smoke Step',
        type: 'special',
        cooldown: 5,
        damage: 65,
        range: 200,
        mpCost: 35,
        description: 'Teleport behind enemy',
      },
      {
        id: 'shadow_clone',
        name: 'Shadow Clone',
        type: 'ultimate',
        cooldown: 15,
        damage: 150,
        range: 300,
        mpCost: 80,
        description: 'Creates temporary ally',
      },
    ],
  },
  hakurou: {
    id: 'hakurou',
    name: 'Hakurou',
    description: 'Sword Saint, master swordsman',
    rarity: 'epic',
    element: 'light',
    category: 'Tensura',
    baseStats: {
      hp: 115,
      mp: 110,
      speed: 6,
      power: 28,
      defense: 14,
      range: 130,
      critChance: 15,
      attack: 280,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'Old ogre swordsman',
        benefits: 'Basic sword techniques',
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 12 },
        statsMultiplier: 1.8,
        lore: 'Sword spirit awakens',
        benefits: 'Sword Flurry and Blade Dance',
      },
      {
        name: 'Sword Saint',
        level: 2,
        requirements: { level: 10, kills: 50 },
        statsMultiplier: 3.5,
        lore: 'Master of all sword techniques',
        benefits: 'Ultimate sword arts',
      },
    ],
    moves: [
      {
        id: 'sword_flurry',
        name: 'Sword Flurry',
        type: 'basic',
        cooldown: 0.6,
        damage: 24,
        range: 120,
        mpCost: 7,
        description: 'Rapid sword strikes',
      },
      {
        id: 'blade_dance',
        name: 'Blade Dance',
        type: 'charge',
        cooldown: 3.5,
        damage: 55,
        range: 140,
        mpCost: 28,
        description: 'Elegant and deadly',
      },
      {
        id: 'iaijutsu',
        name: 'Iaijutsu',
        type: 'special',
        cooldown: 6,
        damage: 75,
        range: 160,
        mpCost: 40,
        description: 'Quick draw technique',
      },
      {
        id: 'saint_technique',
        name: 'Sword Saint Technique',
        type: 'ultimate',
        cooldown: 16,
        damage: 200,
        range: 250,
        mpCost: 90,
        description: 'Legendary sword art',
      },
    ],
  },
  ifrit: {
    id: 'ifrit',
    name: 'Ifrit',
    description: 'Fire Spirit Dragon',
    rarity: 'rare',
    element: 'fire',
    category: 'Dragons',
    baseStats: {
      hp: 150,
      mp: 140,
      speed: 5,
      power: 30,
      defense: 18,
      range: 200,
      critChance: 8,
      attack: 300,
    },
    evolutions: [
      {
        name: 'Hatchling',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'Young fire dragon',
        benefits: 'Basic fire attacks',
      },
      {
        name: 'Fire Drake',
        level: 1,
        requirements: { level: 5, kills: 25 },
        statsMultiplier: 2,
        lore: 'Fire energy catalyzes growth',
        benefits: 'Fireball and Flame Charge',
      },
      {
        name: 'Inferno Dragon',
        level: 2,
        requirements: { level: 10, kills: 80 },
        statsMultiplier: 3.5,
        lore: 'Ascends to dragon supremacy',
        benefits: 'Fire Breath, Heat Wave',
      },
    ],
    moves: [
      {
        id: 'fire_breath',
        name: 'Fire Breath',
        type: 'basic',
        cooldown: 0.7,
        damage: 28,
        range: 180,
        mpCost: 8,
        description: 'Dragon fire',
      },
      {
        id: 'flame_charge',
        name: 'Flame Charge',
        type: 'charge',
        cooldown: 4,
        damage: 60,
        range: 220,
        mpCost: 30,
        description: 'Rush with flames',
      },
      {
        id: 'heat_wave',
        name: 'Heat Wave',
        type: 'special',
        cooldown: 7,
        damage: 85,
        range: 280,
        mpCost: 45,
        description: 'AoE fire damage',
      },
      {
        id: 'inferno',
        name: 'Inferno',
        type: 'ultimate',
        cooldown: 18,
        damage: 220,
        range: 400,
        mpCost: 95,
        description: 'Catastrophic flames',
      },
    ],
  },
  charybdis: {
    id: 'charybdis',
    name: 'Charybdis',
    description: 'Sky Dragon, Megalodon of the Skies',
    rarity: 'epic',
    element: 'water',
    category: 'Dragons',
    baseStats: {
      hp: 140,
      mp: 160,
      speed: 6,
      power: 28,
      defense: 16,
      range: 240,
      critChance: 7,
      attack: 280,
    },
    evolutions: [
      {
        name: 'Young Serpent',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'Aquatic dragon serpent',
        benefits: 'Water control basics',
      },
      {
        name: 'Ocean Leviathan',
        level: 1,
        requirements: { level: 5, kills: 30 },
        statsMultiplier: 2.3,
        lore: 'Absorbing water magic',
        benefits: 'Whirlpool, Tidal Slam',
      },
    ],
    moves: [
      {
        id: 'water_cannon',
        name: 'Water Cannon',
        type: 'basic',
        cooldown: 0.6,
        damage: 26,
        range: 220,
        mpCost: 7,
        description: 'High pressure water',
      },
      {
        id: 'whirlpool',
        name: 'Whirlpool',
        type: 'charge',
        cooldown: 4.5,
        damage: 58,
        range: 260,
        mpCost: 32,
        description: 'Spinning water vortex',
      },
      {
        id: 'tidal_slam',
        name: 'Tidal Slam',
        type: 'special',
        cooldown: 7.5,
        damage: 82,
        range: 300,
        mpCost: 48,
        description: 'Massive water strike',
      },
      {
        id: 'tsunami',
        name: 'Tsunami',
        type: 'ultimate',
        cooldown: 20,
        damage: 240,
        range: 450,
        mpCost: 100,
        description: 'Devastating wave',
      },
    ],
  },
  guy_crimson: {
    id: 'guy_crimson',
    name: 'Guy Crimson',
    description: 'Rouge, Primordial Red',
    rarity: 'legendary',
    element: 'fire',
    category: 'Primordials',
    baseStats: {
      hp: 300,
      mp: 350,
      speed: 8,
      power: 45,
      defense: 30,
      range: 300,
      critChance: 15,
      attack: 450,
    },
    evolutions: [
      {
        name: 'Arch Demon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'Ancient demon of chaos',
        benefits: 'Primordial power',
      },
      {
        name: 'True Demon Lord',
        level: 1,
        requirements: { level: 5, kills: 50 },
        statsMultiplier: 2.8,
        lore: 'Ruler of demons',
        benefits: 'Crimson Authority',
      },
    ],
    moves: [
      {
        id: 'crimson_strike',
        name: 'Crimson Strike',
        type: 'basic',
        cooldown: 0.3,
        damage: 38,
        range: 250,
        mpCost: 10,
        description: 'Red lightning fast',
      },
      {
        id: 'nuclear_flame',
        name: 'Nuclear Flame',
        type: 'charge',
        cooldown: 3.5,
        damage: 85,
        range: 320,
        mpCost: 45,
        description: 'Atomic fire',
      },
      {
        id: 'destruction_wave',
        name: 'Destruction Wave',
        type: 'special',
        cooldown: 6,
        damage: 125,
        range: 380,
        mpCost: 65,
        description: 'Waves of chaos',
      },
      {
        id: 'crimson_end',
        name: 'Crimson End',
        type: 'ultimate',
        cooldown: 18,
        damage: 350,
        range: 500,
        mpCost: 150,
        description: 'The end of everything',
      },
    ],
  },
  testarossa: {
    id: 'testarossa',
    name: 'Testarossa',
    description: 'Blanc, Primordial White',
    rarity: 'legendary',
    element: 'light',
    category: 'Primordials',
    baseStats: {
      hp: 280,
      mp: 340,
      speed: 8,
      power: 42,
      defense: 28,
      range: 290,
      critChance: 14,
      attack: 420,
    },
    evolutions: [
      {
        name: 'Arch Demon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'White demon of precision',
        benefits: 'Light manipulation',
      },
      {
        name: 'Demon Duchess',
        level: 1,
        requirements: { level: 5, kills: 45 },
        statsMultiplier: 2.7,
        lore: 'Master of light and death',
        benefits: 'Death Streak mastery',
      },
    ],
    moves: [
      {
        id: 'light_lance',
        name: 'Light Lance',
        type: 'basic',
        cooldown: 0.4,
        damage: 36,
        range: 240,
        mpCost: 9,
        description: 'Piercing light',
      },
      {
        id: 'death_streak',
        name: 'Death Streak',
        type: 'charge',
        cooldown: 3.8,
        damage: 80,
        range: 300,
        mpCost: 42,
        description: 'Light speed strikes',
      },
      {
        id: 'judgement',
        name: 'Judgement',
        type: 'special',
        cooldown: 6.5,
        damage: 118,
        range: 360,
        mpCost: 62,
        description: 'Divine punishment',
      },
      {
        id: 'white_apocalypse',
        name: 'White Apocalypse',
        type: 'ultimate',
        cooldown: 19,
        damage: 330,
        range: 480,
        mpCost: 145,
        description: 'End in white light',
      },
    ],
  },
  ultima: {
    id: 'ultima',
    name: 'Ultima',
    description: 'Violet, Primordial Purple',
    rarity: 'legendary',
    element: 'darkness',
    category: 'Primordials',
    baseStats: {
      hp: 285,
      mp: 330,
      speed: 9,
      power: 43,
      defense: 26,
      range: 280,
      critChance: 16,
      attack: 430,
    },
    evolutions: [
      {
        name: 'Arch Demon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
        lore: 'Purple demon sadist',
        benefits: 'Torture arts',
      },
      {
        name: 'Demon Duchess',
        level: 1,
        requirements: { level: 5, kills: 48 },
        statsMultiplier: 2.9,
        lore: 'Queen of pain',
        benefits: 'Enhanced cruelty',
      },
    ],
    moves: [
      {
        id: 'violet_strike',
        name: 'Violet Strike',
        type: 'basic',
        cooldown: 0.35,
        damage: 37,
        range: 230,
        mpCost: 9,
        description: 'Purple energy slash',
      },
      {
        id: 'gravity_crush',
        name: 'Gravity Crush',
        type: 'charge',
        cooldown: 3.6,
        damage: 82,
        range: 290,
        mpCost: 43,
        description: 'Crush with gravity',
      },
      {
        id: 'torture_dance',
        name: 'Torture Dance',
        type: 'special',
        cooldown: 6.2,
        damage: 120,
        range: 340,
        mpCost: 63,
        description: 'Sadistic assault',
      },
      {
        id: 'violet_end',
        name: 'Violet End',
        type: 'ultimate',
        cooldown: 18.5,
        damage: 340,
        range: 470,
        mpCost: 148,
        description: 'Beautiful destruction',
      },
    ],
  },
};

export function getCharactersByCategory(category: CharacterCategory): Character[] {
  return Object.values(CHARACTERS).filter(char => char.category === category);
}
