import { Character } from '@/types/game';

export const CHARACTERS: Record<string, Character> = {
  rimuru: {
    id: 'rimuru',
    name: 'Rimuru Tempest',
    description: 'The Slime that became a Demon Lord',
    rarity: 'legendary',
    element: 'water',
    baseStats: {
      hp: 100,
      mp: 150,
      speed: 4,
      power: 15,
      defense: 10,
      range: 200,
    },
    evolutions: [
      {
        name: 'Slime',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Human Form',
        level: 1,
        requirements: { level: 5, kills: 10 },
        statsMultiplier: 1.5,
      },
      {
        name: 'Demon Lord',
        level: 2,
        requirements: { level: 10, kills: 50 },
        statsMultiplier: 2.5,
      },
    ],
    moves: [
      {
        id: 'water_blade',
        name: 'Water Blade',
        type: 'basic',
        cooldown: 0.5,
        damage: 15,
        range: 150,
        mpCost: 5,
        description: 'A quick water slash',
      },
      {
        id: 'predator',
        name: 'Predator',
        type: 'charge',
        cooldown: 3,
        damage: 40,
        range: 100,
        mpCost: 20,
        description: 'Devour enemies in range',
      },
      {
        id: 'black_lightning',
        name: 'Black Lightning',
        type: 'special',
        cooldown: 5,
        damage: 60,
        range: 250,
        mpCost: 40,
        description: 'Lightning storm attack',
      },
      {
        id: 'megiddo',
        name: 'Megiddo',
        type: 'ultimate',
        cooldown: 15,
        damage: 150,
        range: 400,
        mpCost: 80,
        description: 'Ultimate magical destruction',
      },
    ],
  },
  benimaru: {
    id: 'benimaru',
    name: 'Benimaru',
    description: 'Commander of Tempest, wielder of flames',
    rarity: 'epic',
    element: 'fire',
    baseStats: {
      hp: 120,
      mp: 100,
      speed: 5,
      power: 20,
      defense: 12,
      range: 180,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 15 },
        statsMultiplier: 1.6,
      },
      {
        name: 'Fair Oni',
        level: 2,
        requirements: { level: 10, kills: 60 },
        statsMultiplier: 2.8,
      },
    ],
    moves: [
      {
        id: 'flame_slash',
        name: 'Flame Slash',
        type: 'basic',
        cooldown: 0.6,
        damage: 20,
        range: 120,
        mpCost: 5,
        description: 'Flaming sword strike',
      },
      {
        id: 'hell_flare',
        name: 'Hell Flare',
        type: 'charge',
        cooldown: 3.5,
        damage: 50,
        range: 200,
        mpCost: 25,
        description: 'Explosive fire burst',
      },
      {
        id: 'black_flame',
        name: 'Black Flame',
        type: 'special',
        cooldown: 6,
        damage: 70,
        range: 220,
        mpCost: 45,
        description: 'Dark hellfire',
      },
      {
        id: 'flame_giant',
        name: 'Flame Giant',
        type: 'ultimate',
        cooldown: 18,
        damage: 180,
        range: 350,
        mpCost: 90,
        description: 'Summon massive fire demon',
      },
    ],
  },
  milim: {
    id: 'milim',
    name: 'Milim Nava',
    description: 'The Destroyer, oldest Demon Lord',
    rarity: 'legendary',
    element: 'storm',
    baseStats: {
      hp: 150,
      mp: 200,
      speed: 6,
      power: 30,
      defense: 15,
      range: 250,
    },
    evolutions: [
      {
        name: 'Base Form',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Dragonoid',
        level: 1,
        requirements: { level: 5, kills: 20 },
        statsMultiplier: 2,
      },
      {
        name: 'True Dragonoid',
        level: 2,
        requirements: { level: 10, kills: 80 },
        statsMultiplier: 3.5,
      },
    ],
    moves: [
      {
        id: 'dragonic_punch',
        name: 'Dragonic Punch',
        type: 'basic',
        cooldown: 0.4,
        damage: 25,
        range: 100,
        mpCost: 5,
        description: 'Powerful melee strike',
      },
      {
        id: 'drago_nova',
        name: 'Drago Nova',
        type: 'charge',
        cooldown: 4,
        damage: 60,
        range: 300,
        mpCost: 30,
        description: 'Energy explosion',
      },
      {
        id: 'drago_buster',
        name: 'Drago Buster',
        type: 'special',
        cooldown: 7,
        damage: 90,
        range: 350,
        mpCost: 50,
        description: 'Destructive dragon breath',
      },
      {
        id: 'wrath_king',
        name: 'Wrath King Satan',
        type: 'ultimate',
        cooldown: 20,
        damage: 250,
        range: 500,
        mpCost: 100,
        description: 'Catastrophic destruction',
      },
    ],
  },
  shion: {
    id: 'shion',
    name: 'Shion',
    description: 'Loyal secretary with deadly strength',
    rarity: 'epic',
    element: 'darkness',
    baseStats: {
      hp: 130,
      mp: 80,
      speed: 4,
      power: 25,
      defense: 18,
      range: 120,
    },
    evolutions: [
      {
        name: 'Ogre',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin',
        level: 1,
        requirements: { level: 5, kills: 15 },
        statsMultiplier: 1.7,
      },
      {
        name: 'Oni',
        level: 2,
        requirements: { level: 10, kills: 65 },
        statsMultiplier: 3,
      },
    ],
    moves: [
      {
        id: 'crushing_blow',
        name: 'Crushing Blow',
        type: 'basic',
        cooldown: 0.7,
        damage: 22,
        range: 100,
        mpCost: 5,
        description: 'Heavy sword strike',
      },
      {
        id: 'berserker',
        name: 'Berserker',
        type: 'charge',
        cooldown: 4,
        damage: 55,
        range: 150,
        mpCost: 20,
        description: 'Rage-fueled assault',
      },
      {
        id: 'hercules_edge',
        name: 'Hercules Edge',
        type: 'special',
        cooldown: 8,
        damage: 80,
        range: 180,
        mpCost: 35,
        description: 'Ultimate sword technique',
      },
      {
        id: 'cook_slash',
        name: 'Cook Slash',
        type: 'ultimate',
        cooldown: 16,
        damage: 160,
        range: 250,
        mpCost: 75,
        description: 'Culinary catastrophe',
      },
    ],
  },
  diablo: {
    id: 'diablo',
    name: 'Diablo',
    description: 'Primordial Black Demon',
    rarity: 'legendary',
    element: 'darkness',
    baseStats: {
      hp: 140,
      mp: 220,
      speed: 7,
      power: 35,
      defense: 20,
      range: 280,
    },
    evolutions: [
      {
        name: 'Arch Demon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Demon Lord',
        level: 1,
        requirements: { level: 5, kills: 25 },
        statsMultiplier: 2.2,
      },
      {
        name: 'Primordial Black',
        level: 2,
        requirements: { level: 10, kills: 100 },
        statsMultiplier: 4,
      },
    ],
    moves: [
      {
        id: 'death_streak',
        name: 'Death Streak',
        type: 'basic',
        cooldown: 0.3,
        damage: 28,
        range: 200,
        mpCost: 8,
        description: 'Rapid dark strikes',
      },
      {
        id: 'temptation',
        name: 'Temptation',
        type: 'charge',
        cooldown: 3,
        damage: 65,
        range: 280,
        mpCost: 35,
        description: 'Seductive dark magic',
      },
      {
        id: 'void_collapse',
        name: 'Void Collapse',
        type: 'special',
        cooldown: 6,
        damage: 95,
        range: 320,
        mpCost: 55,
        description: 'Collapse space itself',
      },
      {
        id: 'apocalypse',
        name: 'Apocalypse',
        type: 'ultimate',
        cooldown: 18,
        damage: 280,
        range: 450,
        mpCost: 110,
        description: 'End of all things',
      },
    ],
  },
  veldora: {
    id: 'veldora',
    name: 'Veldora',
    description: 'Storm Dragon, True Dragon',
    rarity: 'legendary',
    element: 'storm',
    baseStats: {
      hp: 180,
      mp: 250,
      speed: 5,
      power: 40,
      defense: 25,
      range: 300,
    },
    evolutions: [
      {
        name: 'Sealed Dragon',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Released Dragon',
        level: 1,
        requirements: { level: 5, kills: 30 },
        statsMultiplier: 2.5,
      },
      {
        name: 'True Dragon',
        level: 2,
        requirements: { level: 10, kills: 120 },
        statsMultiplier: 4.5,
      },
    ],
    moves: [
      {
        id: 'storm_breath',
        name: 'Storm Breath',
        type: 'basic',
        cooldown: 0.5,
        damage: 30,
        range: 250,
        mpCost: 10,
        description: 'Lightning breath attack',
      },
      {
        id: 'death_heralding_wind',
        name: 'Death Heralding Wind',
        type: 'charge',
        cooldown: 4.5,
        damage: 70,
        range: 300,
        mpCost: 40,
        description: 'Catastrophic storm',
      },
      {
        id: 'dragon_nova',
        name: 'Dragon Nova',
        type: 'special',
        cooldown: 8,
        damage: 110,
        range: 350,
        mpCost: 65,
        description: 'True Dragon power',
      },
      {
        id: 'chaos_storm',
        name: 'Chaos Storm',
        type: 'ultimate',
        cooldown: 22,
        damage: 320,
        range: 500,
        mpCost: 130,
        description: 'Apocalyptic tempest',
      },
    ],
  },
  shuna: {
    id: 'shuna',
    name: 'Shuna',
    description: 'Princess of Ogres, master analyst',
    rarity: 'rare',
    element: 'light',
    baseStats: {
      hp: 90,
      mp: 180,
      speed: 5,
      power: 18,
      defense: 8,
      range: 220,
    },
    evolutions: [
      {
        name: 'Ogre Princess',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Kijin Princess',
        level: 1,
        requirements: { level: 5, kills: 12 },
        statsMultiplier: 1.8,
      },
      {
        name: 'Divine Princess',
        level: 2,
        requirements: { level: 10, kills: 50 },
        statsMultiplier: 2.6,
      },
    ],
    moves: [
      {
        id: 'holy_bolt',
        name: 'Holy Bolt',
        type: 'basic',
        cooldown: 0.6,
        damage: 16,
        range: 200,
        mpCost: 7,
        description: 'Sacred light projectile',
      },
      {
        id: 'analyzer',
        name: 'Analyzer',
        type: 'charge',
        cooldown: 3.5,
        damage: 38,
        range: 220,
        mpCost: 22,
        description: 'Analyze and exploit weakness',
      },
      {
        id: 'spirit_blessing',
        name: 'Spirit Blessing',
        type: 'special',
        cooldown: 7,
        damage: 55,
        range: 240,
        mpCost: 40,
        description: 'Divine spirit power',
      },
      {
        id: 'divine_judgment',
        name: 'Divine Judgment',
        type: 'ultimate',
        cooldown: 15,
        damage: 140,
        range: 300,
        mpCost: 85,
        description: 'Heaven\'s wrath',
      },
    ],
  },
  ranga: {
    id: 'ranga',
    name: 'Ranga',
    description: 'Tempest Star Wolf, loyal companion',
    rarity: 'rare',
    element: 'storm',
    baseStats: {
      hp: 110,
      mp: 120,
      speed: 7,
      power: 20,
      defense: 12,
      range: 140,
    },
    evolutions: [
      {
        name: 'Dire Wolf',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Tempest Wolf',
        level: 1,
        requirements: { level: 5, kills: 18 },
        statsMultiplier: 1.9,
      },
      {
        name: 'Star Wolf',
        level: 2,
        requirements: { level: 10, kills: 70 },
        statsMultiplier: 3.2,
      },
    ],
    moves: [
      {
        id: 'fang_strike',
        name: 'Fang Strike',
        type: 'basic',
        cooldown: 0.4,
        damage: 18,
        range: 120,
        mpCost: 4,
        description: 'Swift bite attack',
      },
      {
        id: 'lightning_claw',
        name: 'Lightning Claw',
        type: 'charge',
        cooldown: 3,
        damage: 42,
        range: 150,
        mpCost: 18,
        description: 'Electrified slash',
      },
      {
        id: 'tempest_howl',
        name: 'Tempest Howl',
        type: 'special',
        cooldown: 6,
        damage: 62,
        range: 200,
        mpCost: 32,
        description: 'Storm-summoning roar',
      },
      {
        id: 'black_lightning',
        name: 'Black Lightning',
        type: 'ultimate',
        cooldown: 14,
        damage: 145,
        range: 280,
        mpCost: 70,
        description: 'Devastating storm strike',
      },
    ],
  },
  gobta: {
    id: 'gobta',
    name: 'Gobta',
    description: 'Hobgoblin ninja, comic relief hero',
    rarity: 'common',
    element: 'water',
    baseStats: {
      hp: 80,
      mp: 100,
      speed: 6,
      power: 12,
      defense: 8,
      range: 160,
    },
    evolutions: [
      {
        name: 'Goblin',
        level: 0,
        requirements: { level: 0 },
        statsMultiplier: 1,
      },
      {
        name: 'Hobgoblin',
        level: 1,
        requirements: { level: 5, kills: 10 },
        statsMultiplier: 1.6,
      },
      {
        name: 'Gob Ninja',
        level: 2,
        requirements: { level: 10, kills: 40 },
        statsMultiplier: 2.4,
      },
    ],
    moves: [
      {
        id: 'ninja_strike',
        name: 'Ninja Strike',
        type: 'basic',
        cooldown: 0.5,
        damage: 14,
        range: 140,
        mpCost: 4,
        description: 'Quick ninja attack',
      },
      {
        id: 'shadow_clone',
        name: 'Shadow Clone',
        type: 'charge',
        cooldown: 3.5,
        damage: 32,
        range: 160,
        mpCost: 16,
        description: 'Confusing clone jutsu',
      },
      {
        id: 'water_shuriken',
        name: 'Water Shuriken',
        type: 'special',
        cooldown: 6.5,
        damage: 48,
        range: 180,
        mpCost: 28,
        description: 'Spinning water blades',
      },
      {
        id: 'ultimate_ninja',
        name: 'Ultimate Ninja Art',
        type: 'ultimate',
        cooldown: 13,
        damage: 120,
        range: 240,
        mpCost: 65,
        description: 'Secret technique!',
      },
    ],
  },
};
