import { Upgrade, Artifact } from '@/types/game';

export const UPGRADES: Record<string, Upgrade> = {
  hp_boost: {
    id: 'hp_boost',
    name: 'HP Boost',
    description: 'Increase maximum HP',
    type: 'stat',
    cost: 100,
    level: 0,
    maxLevel: 10,
    effect: { hpBonus: 20 },
  },
  mp_boost: {
    id: 'mp_boost',
    name: 'MP Boost',
    description: 'Increase maximum MP',
    type: 'stat',
    cost: 100,
    level: 0,
    maxLevel: 10,
    effect: { mpBonus: 20 },
  },
  power_boost: {
    id: 'power_boost',
    name: 'Power Boost',
    description: 'Increase attack power',
    type: 'stat',
    cost: 150,
    level: 0,
    maxLevel: 10,
    effect: { powerBonus: 5 },
  },
  defense_boost: {
    id: 'defense_boost',
    name: 'Defense Boost',
    description: 'Increase defense',
    type: 'stat',
    cost: 150,
    level: 0,
    maxLevel: 10,
    effect: { defenseBonus: 3 },
  },
  speed_boost: {
    id: 'speed_boost',
    name: 'Speed Boost',
    description: 'Increase movement speed',
    type: 'stat',
    cost: 200,
    level: 0,
    maxLevel: 5,
    effect: { speedBonus: 0.5 },
  },
  range_boost: {
    id: 'range_boost',
    name: 'Range Boost',
    description: 'Increase attack range',
    type: 'stat',
    cost: 180,
    level: 0,
    maxLevel: 8,
    effect: { rangeBonus: 20 },
  },
};

export const ARTIFACTS: Record<string, Artifact> = {
  slime_ring: {
    id: 'slime_ring',
    name: 'Slime Ring',
    description: 'Grants HP regeneration',
    cost: 500,
    rarity: 'common',
    effect: '+2 HP/sec',
  },
  mana_crystal: {
    id: 'mana_crystal',
    name: 'Mana Crystal',
    description: 'Increases MP regeneration',
    cost: 500,
    rarity: 'common',
    effect: '+3 MP/sec',
  },
  berserker_armor: {
    id: 'berserker_armor',
    name: 'Berserker Armor',
    description: 'Increases attack at low HP',
    cost: 800,
    rarity: 'rare',
    effect: '+50% power below 30% HP',
  },
  phoenix_feather: {
    id: 'phoenix_feather',
    name: 'Phoenix Feather',
    description: 'Revive once per run',
    cost: 1500,
    rarity: 'epic',
    effect: 'Revive with 50% HP',
  },
  demon_blade: {
    id: 'demon_blade',
    name: 'Demon Blade',
    description: 'Greatly increases damage',
    cost: 1200,
    rarity: 'epic',
    effect: '+30% damage',
  },
  dragon_scale: {
    id: 'dragon_scale',
    name: 'Dragon Scale',
    description: 'Reduces damage taken',
    cost: 1200,
    rarity: 'epic',
    effect: '-25% damage taken',
  },
  true_dragon_orb: {
    id: 'true_dragon_orb',
    name: 'True Dragon Orb',
    description: 'Massive stat boost',
    cost: 3000,
    rarity: 'legendary',
    effect: '+50% all stats',
  },
  infinity_gem: {
    id: 'infinity_gem',
    name: 'Infinity Gem',
    description: 'Infinite MP for 10 seconds',
    cost: 2500,
    rarity: 'legendary',
    effect: 'Ultimate costs no MP',
  },
};

export const CHARACTER_UNLOCK_COSTS: Record<string, number> = {
  rimuru: 0,
  gobta: 0,
  benimaru: 1000,
  shuna: 800,
  ranga: 800,
  shion: 1500,
  milim: 3000,
  diablo: 5000,
  veldora: 8000,
};
